version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to DockerHub
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
  build:
    commands:
      - echo Building Docker image
      - docker build -t vennilavan/dev:latest .

  post_build:
    commands:
      - echo Pushing Docker image to DockerHub
      - docker push vennilavan/dev:latest

artifacts:
  files: Dockerrun.aws.json
